- name: Create an EKS cluster
  shell: >
    eksctl create cluster \
    --name {{ eksexample_clustername }} \
    --version {{ eksexample_clusterversion }} \
    --region {{ eksexample_region }} \
    --nodegroup-name {{ eksexample_clustername }}-linux-nodes \
    --node-type t3a.small \
    --nodes-min 1 \
    --nodes-max 1 \
    --managed
  when: eks_check_output.stdout == "No clusters found"
