- hosts: 127.0.0.1
  connection: local

  tasks:

  - name: Create an EKS cluster
    shell: eksctl create cluster \
      --name siamsot-capstone \
      --version 1.17 \
      --region eu-west-2 \
      --nodegroup-name siamsot-linux-nodes \
      --node-type t3a.small \
      --nodes-min 1 \
      --nodes-max 2 \
      --managed
  - name: Update kubeconfig
    command: aws eks --region eu-west-2 update-kubeconfig --name siamsot-capstone
